[package]
name = "flashblocks-compression"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
tracing.workspace = true
tokio.workspace = true
eyre.workspace = true
sha2.workspace = true

reqwest = { version = "0.12.15", default-features = false, features = ["native-tls"] }
brotli = "8.0.1"
zstd-safe = { version = "7.2.4", features = ["experimental"] }

[dev-dependencies]
tokio.workspace = true
axum = { version = "0.8.1", features = ["ws"] }

